ALTER TABLE category_description ADD COLUMN `title` VARCHAR(255) NULL;

UPDATE category_description SET `title` = 'Купить табак для кальяна - Golden Shisha',`meta_description` = 'Интернет-магазин Golden Shisha - популярные и эксклюзивные табаки для кальяна с доставкой по всей Украине.' WHERE `category_id` = '1' AND `language_id` = '1';
UPDATE category_description SET `title` = 'Купить табак для кальяна - Golden Shisha',`meta_description` = 'Интернет-магазин Golden Shisha - популярные и эксклюзивные табаки для кальяна с доставкой по всей Украине.' WHERE `category_id` = '1' AND `language_id` = '2';
UPDATE category_description SET `title` = 'Купить кальян с доставкой по Украине - Golden Shisha',`meta_description` = 'Интернет-магазин Golden Shisha - качественные кальяны в магазине в Харькове или с доставкой почтой по Украине.' WHERE `category_id` = '14' AND `language_id` = '1';
UPDATE category_description SET `title` = 'Купить кальян с доставкой по Украине - Golden Shisha',`meta_description` = 'Интернет-магазин Golden Shisha - качественные кальяны в магазине в Харькове или с доставкой почтой по Украине.' WHERE `category_id` = '14' AND `language_id` = '2';
UPDATE category_description SET `title` = 'Купить кокосовый уголь для кальяна - Golden Shisha',`meta_description` = 'Уголь с доставкой почтой по Украине или в магазине в Харькове из натуральных компонентов.' WHERE `category_id` = '15' AND `language_id` = '1';
UPDATE category_description SET `title` = 'Купить кокосовый уголь для кальяна - Golden Shisha',`meta_description` = 'Уголь с доставкой почтой по Украине или в магазине в Харькове из натуральных компонентов.' WHERE `category_id` = '15' AND `language_id` = '2';
UPDATE category_description SET `title` = 'Аксессуары для кальяна - интернет-магазин Golden Shisha',`meta_description` = 'Аксессуары для кальяна с доставкой по Украине или в магазине в Харькове. Колбы, мундштуки, держатели, ерш для чистки шахты.' WHERE `category_id` = '16' AND `language_id` = '1';
UPDATE category_description SET `title` = 'Аксессуары для кальяна - интернет-магазин Golden Shisha',`meta_description` = 'Аксессуары для кальяна с доставкой по Украине или в магазине в Харькове. Колбы, мундштуки, держатели, ерш для чистки шахты.' WHERE `category_id` = '16' AND `language_id` = '2';
UPDATE category_description SET `title` = 'Купить чашу для кальяна с доставкой по Украине - Golden Shisha',`meta_description` = 'Чаши для кальяна из силикона и глины с доставкой по Украине или в магазинах Харькова - интернет-магазин Golden Shisha' WHERE `category_id` = '17' AND `language_id` = '1';
UPDATE category_description SET `title` = 'Купить чашу для кальяна с доставкой по Украине - Golden Shisha',`meta_description` = 'Чаши для кальяна из силикона и глины с доставкой по Украине или в магазинах Харькова - интернет-магазин Golden Shisha' WHERE `category_id` = '17' AND `language_id` = '2';
UPDATE category_description SET `title` = 'Купить калауд для кальяна с доставкой по Украине - Golden Shisha',`meta_description` = 'Регулируйте передачу тепла от угля к чаше, а также равномерно его распределяйте с помощью калауда.' WHERE `category_id` = '18' AND `language_id` = '1';
UPDATE category_description SET `title` = 'Купить калауд для кальяна с доставкой по Украине - Golden Shisha',`meta_description` = 'Регулируйте передачу тепла от угля к чаше, а также равномерно его распределяйте с помощью калауда.' WHERE `category_id` = '18' AND `language_id` = '2';